# Generated by Django 4.1 on 2022-12-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirect',
            old_name='after_password_reset',
            new_name='after_email_verification',
        ),
    ]
