# Generated by Django 4.1 on 2022-12-16 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_rename_after_password_reset_redirect_after_email_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirect',
            name='id',
        ),
        migrations.AlterField(
            model_name='redirect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
