# Generated by Django 4.1 on 2022-12-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbanevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='kanbanevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='KanbanCategory',
        ),
        migrations.DeleteModel(
            name='KanbanEvent',
        ),
    ]
