# Generated by Django 4.1 on 2022-12-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='redirect_to',
            field=models.CharField(default='', help_text='Url redirect to after email verification and password reset.', max_length=126, verbose_name='redirect_to'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this users email should is verified.', verbose_name='email_verified'),
        ),
    ]
