# Generated by Django 4.1 on 2022-12-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_googlecredentials_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlecredentials',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
