# Generated by Django 4.1 on 2022-12-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_kanbancategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='redirect_after_login',
            field=models.TextField(null=True),
        ),
    ]
