# Generated by Django 4.1 on 2022-12-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_googlecredentials_redirect_after_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='available_social_networks',
            field=models.IntegerField(default=1),
        ),
    ]
