# Generated by Django 4.1 on 2022-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_myuser_created_at_alter_myuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
