# Generated by Django 4.1 on 2022-12-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_myuser_available_social_networks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='available_social_networks',
        ),
        migrations.AddField(
            model_name='myuser',
            name='connected_social_networks',
            field=models.IntegerField(default=0),
        ),
    ]
