# Generated by Django 4.1 on 2022-12-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_myuser_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='subscription',
        ),
    ]
