# Generated by Django 4.1 on 2022-12-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tiktokcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokcredentials',
            name='redirect_after_login',
            field=models.TextField(null=True),
        ),
    ]
