# Generated by Django 4.1 on 2022-12-14 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_myuser_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbanevent',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='kanbancategories',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kanbanevent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kanbancategories'),
        ),
        migrations.AddField(
            model_name='kanbanevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kanbanevent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kanbanevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='kanbanevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
