# Generated by Django 4.1 on 2022-12-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tiktokcredentials_redirect_after_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='on_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='statisticmetric',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='StatisticMetricToMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.metricvalue')),
                ('statistic_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.statisticmetric')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworkToStatisticMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.contenttype')),
                ('social_network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.socialnetwork')),
            ],
        ),
    ]
