# Generated by Django 4.1 on 2022-12-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_kanbanevent_options_kanbancategories_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KanbanCategories',
            new_name='KanbanCategory',
        ),
    ]
