# Generated by Django 4.1 on 2022-12-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_kanbancategory_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KanbanCategory',
        ),
    ]
