# Generated by Django 4.1 on 2022-12-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_socialnetworktostatisticmetric_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('on_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StatisticMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StatisticMetricToMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.metricvalue')),
                ('statistic_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.statisticmetric')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworkToStatisticMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.socialnetwork')),
                ('user_metric', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.statisticmetric')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworkToContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.contenttype')),
                ('social_network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.socialnetwork')),
            ],
        ),
    ]
