# Generated by Django 4.1 on 2022-12-19 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contenttype_metricvalue_socialnetwork_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.socialnetwork')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
