# Generated by Django 4.1 on 2022-12-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_usertosocialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
