# Generated by Django 4.1 on 2022-12-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_kanbanevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbancategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='kanbancategory',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
