# Generated by Django 4.1 on 2022-12-19 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_socialnetwork_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertosocialnetwork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
