# Generated by Django 4.1 on 2022-12-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_kanbancategory_id_alter_kanbancategory_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KanbanEvent',
        ),
    ]
