# Generated by Django 4.1 on 2022-12-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contenttypetometricvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentTypeToMetricValue',
        ),
    ]
