# Generated by Django 4.1 on 2022-12-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_contenttypetometricvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTypeToStatisticMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.contenttype')),
                ('statistic_metric', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.statisticmetric')),
            ],
        ),
    ]
