# Generated by Django 4.1 on 2022-12-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_calendarevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='is_all_day',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='subject',
            field=models.CharField(max_length=64),
        ),
    ]
