# Generated by Django 4.1 on 2022-12-19 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_socialnetworktocontenttype_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkToStatisticMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserToSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.socialnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticMetricToMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.metricvalue')),
                ('statistic_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.socialnetworktostatisticmetric')),
            ],
        ),
        migrations.AddField(
            model_name='socialnetworktostatisticmetric',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertosocialnetwork'),
        ),
        migrations.AddField(
            model_name='socialnetworktostatisticmetric',
            name='user_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.statisticmetric'),
        ),
        migrations.CreateModel(
            name='SocialNetworkToContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.contenttype')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertosocialnetwork')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTypeToStatisticMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.socialnetworktocontenttype')),
                ('statistic_metric', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.statisticmetric')),
            ],
        ),
    ]
