# Generated by Django 4.1 on 2022-12-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_calendarevent_recurrence_exception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='redirect_to',
        ),
    ]
