# Generated by Django 4.1 on 2022-12-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('stripe_id', models.CharField(max_length=19, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=36)),
                ('description', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('stripe_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('per_unit', models.DecimalField(decimal_places=4, max_digits=6)),
                ('period', models.CharField(max_length=16)),
                ('currency', models.CharField(max_length=16)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=126)),
                ('product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.product')),
            ],
        ),
    ]
