# Generated by Django 4.1 on 2022-12-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptions_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.product'),
        ),
    ]
