# Generated by Django 4.1 on 2022-12-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_feature_created_at_alter_feature_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product_id',
        ),
        migrations.CreateModel(
            name='PriceToProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.price')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.product')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureToProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.feature')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.product')),
            ],
        ),
    ]
