# Generated by Django 4.1 on 2022-12-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_feature_product_id_remove_price_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuretoproduct',
            old_name='feature_id',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='featuretoproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='pricetoproduct',
            old_name='price_id',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pricetoproduct',
            old_name='product_id',
            new_name='product',
        ),
    ]
