# Generated by Django 4.1 on 2022-12-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_rename_feature_id_featuretoproduct_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.feature')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='pricetoproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pricetoproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='FeatureToProduct',
        ),
        migrations.DeleteModel(
            name='PriceToProduct',
        ),
    ]
