# Generated by Django 4.1 on 2022-12-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_delete_productpricefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.ManyToManyField(to='subscriptions.feature')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.price')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.product')),
            ],
        ),
    ]
