# Generated by Django 4.1 on 2022-12-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='subscription_id',
            new_name='subscription',
        ),
    ]
