# Generated by Django 4.1 on 2022-12-14 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0013_rename_subscription_id_subscriptions_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
