# Generated by Django 4.1 on 2022-12-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_remove_subscriptions_id_alter_subscriptions_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='price',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='price',
            name='updated_at',
        ),
    ]
